{
    "name": "Custom Recruitment",
    "version": "17.0.1.0.0",
    "summary": """""",
    "author": "Space-o Technology",
    "website": "",
    "company": "Space-o Technology",
    "maintainer": "Space-o Technology",
    "category": "Human Resource",
    "license": "LGPL-3",
    "depends": [
        "base",
        "hr_recruitment",
        "hr_recruitment_skills",
        "mail",
        "utm",
        "calendar",
    ],
    "data": [
        "data/source_demo_data.xml",
        "security/recruitment_security.xml",
        "data/candidate_email_template.xml",
        "data/email_scheduler.xml",
        "data/scheduler_email_template.xml",
        "data/mail_template_data.xml",
        "security/ir.model.access.csv",
        "wizard/interview_schedule_wizard_view.xml",
        "wizard/send_review_form_wizard_view.xml",
        "view/custom_job_recruitment_view.xml",
        "view/candidate_call_master_view.xml",
        "view/candidate_portal_form_template.xml",
        "view/res_config_view.xml",
        "view/candidate_evaluation_form_template.xml",
        "view/templates.xml",
    ],
    "assets": {
        "web.assets_frontend": [
            "custom_recruitment/static/src/js/candidate_portal_form.js",
        ],
    },
    "installable": True,
    "auto_install": False,
    "application": True,
}
